[General]
# 日志级别
loglevel = notify
# 出网探测
internet-test-url = http://wifi.vivo.com.cn/generate_204
# 节点探测
proxy-test-url = http://cp.cloudflare.com/generate_204
# 探测超时
test-timeout = 5
# UDP 探测
proxy-test-udp = google.com@8.8.8.8
# 明文 DNS 兜底
dns-server = system
# 加密 DNS（IP，无 bootstrap）
encrypted-dns-server = https://1.1.1.1/dns-query, https://8.8.8.8/dns-query
# DoH 走规则
encrypted-dns-follow-outbound-mode = true
# 校验证书
encrypted-dns-skip-cert-verification = false
# 劫持 :53
hijack-dns = *:53
# 短名不走代理
exclude-simple-hostnames = true
# 关 IPv6
ipv6 = false
# 关 IPv6 VIF
ipv6-vif = disabled
# UDP 不支持则拒绝
udp-policy-not-supported-behaviour = REJECT
# 关游戏模式
udp-priority = false
# REJECT 显示错误页
show-error-page-for-reject = true
# GEOIP 库
geoip-maxmind-url = https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country-without-asn.mmdb
# 系统代理旁路
skip-proxy = 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, *.local, localhost

[Proxy]
HK = snell, 1.1.1.1, 443, psk=3PTIi3AH6tYsrqJ4sXWkienh, version=6, mode=default, reuse=true
US = snell, 8.8.8.8, 443, psk=bj6A7tQg9KLzCGd62kGjrpN4, version=6, mode=default, reuse=true

[Proxy Group]
Final = select, HK, US, DIRECT, no-alert=0, hidden=0, include-all-proxies=0, icon-url=B1::User Interface::Final State

[Rule]
AND,((DOMAIN-SUFFIX,googlevideo.com), (PROTOCOL,UDP)),REJECT
AND,((DOMAIN,youtubei.googleapis.com), (PROTOCOL,UDP)),REJECT
RULE-SET,https://raw.githubusercontent.com/Repcz/Tool/refs/heads/X/Surge/Rules/Reject.list,REJECT,pre-matching,extended-matching
RULE-SET,https://raw.githubusercontent.com/Repcz/Tool/refs/heads/X/Surge/Rules/AI.list,US
RULE-SET,https://raw.githubusercontent.com/Repcz/Tool/refs/heads/X/Surge/Rules/ChinaDomain.list,DIRECT,extended-matching
RULE-SET,https://raw.githubusercontent.com/Repcz/Tool/refs/heads/X/Surge/Rules/Apple.list,DIRECT
RULE-SET,SYSTEM,DIRECT
RULE-SET,LAN,DIRECT
GEOIP,CN,DIRECT,no-resolve
FINAL,Final,dns-failed

[Host]
RULE-SET:https://raw.githubusercontent.com/Repcz/Tool/refs/heads/X/Surge/Rules/ChinaDomain.list = server:https://223.5.5.5/dns-query, https://223.6.6.6/dns-query

[URL Rewrite]
^https?:\/\/(www.)?(g|google)\.cn https://www.google.com 307
^https?:\/\/(ditu|maps).google\.cn https://maps.google.com 307

[Map Local]
^https?:\/\/[\w-]+\.googlevideo\.com\/initplayback.+&oad data-type=text status-code=200

[MITM]
skip-server-cert-verify = true
h2 = true
hostname = *.googlevideo.com, youtubei.googleapis.com, www.google.cn

[Script]
youtube.response = type=http-response,pattern=^https:\/\/youtubei\.googleapis\.com\/(youtubei\/v1\/(browse|next|player|search|reel\/reel_watch_sequence|guide|account\/get_setting|get_watch))(\?.*)?$,requires-body=1,max-size=-1,binary-body-mode=1,script-path=https://raw.githubusercontent.com/Maasea/sgmodule/master/Script/Youtube/youtube.response.js,argument="{"lyricLang":"off","captionLang":"off","blockUpload":true,"blockImmersive":true,"blockShorts":false,"debug":false}"
